name: macApp Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # 改为 macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "13.x"
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      - run: flutter --version
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Start build
        run: make macapp
      
      # 新增：安装 create-dmg
      - name: Install create-dmg
        run: brew install create-dmg

      - name: Start build
        run: make macapp

      # Upload generated dmg to the release.
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "DEVTools.dmg"
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.TOKEN }}
